# This will deploy Redis on the local machine as a single Docker container: redis
# Redisr is available to the local clients using URL: "redis://localhost:6379"
# Deploy using: docker-compose -f docker-compose-redis.yml up
# <CTRL-C> will stop the container
# Clean-up using: docker-compose -f docker-compose-redis.yml down
version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
