version: '3'
services:

  datahub-a:
    # build: .
    image: 4cloudsolutions/helix-datahub:v1
    ports:
      - "9090:9090"
    # env_file: .env
    environment:
      JAVA_OPTS:
      PORT: 9090
      DATAHUB_CONFIG_FILE: config1.yml
      REDIS_URL: redis://192.168.0.251:6379
      REDIS_URL_B: redis://192.168.0.251:6380
      HELIX_REPLICATION_ROLE: A
      HELIX_REPLICATION_HOSTS: 192.168.0.251:9092
    # volumes:
    #   - .:/app

  datahub-b:
    # build: .
    image: 4cloudsolutions/helix-datahub:v1
    ports:
      - "9096:9090"
    # env_file: .env
    environment:
      JAVA_OPTS:
      PORT: 9090
      DATAHUB_CONFIG_FILE: config1.yml
      REDIS_URL: redis://192.168.0.251:6379
      REDIS_URL_B: redis://192.168.0.251:6380
      HELIX_REPLICATION_ROLE: B
      HELIX_REPLICATION_HOSTS: 192.168.0.251:9092
    # volumes:
    #   - .:/app
